pipeline {
    agent any
    
    stages {
        stage('Pull Git Content') {
            steps {
                script {
                    git url: 'https://github.com/nagvadraj/IntellipaatProjects.git', branch: 'test'
                }
            }
        }
    }
}
