pipeline {
    agent any
    
    stages {
        stage('Pull Git Content') {
            steps {
                script {
                    sh 'develop'
                }
                
                dir('createdbyJenkinsPipeline') {
                    git url: 'https://github.com/nagvadraj/IntellipaatProjects.git', branch: 'main'
                }
            }
        }
    }
}
